#!/bin/bash
set -e

BRANCH="test-delete-autogenerated"
FILES=("src/pages/contributors.json" "src/pages/adp-site-metadata.json")

git checkout main
git pull

git branch -D "$BRANCH" 2>/dev/null || true
git push origin --delete "$BRANCH" 2>/dev/null || true

git checkout -b "$BRANCH"

DELETED=0
for f in "${FILES[@]}"; do
  if [ -f "$f" ]; then
    git rm "$f"
    DELETED=$((DELETED + 1))
  fi
done

if [ "$DELETED" -eq 0 ]; then
  echo "No auto-generated files found — nothing to delete."
  git checkout main
  git branch -d "$BRANCH"
  exit 0
fi

git commit -m "test: remove auto-generated files to trigger deploy workflow push"
git push -u origin "$BRANCH"

PR_URL=$(gh pr create --title "test: remove auto-generated files" --body "Triggers deploy workflow to re-generate and push contributors.json and adp-site-metadata.json." --base main --head "$BRANCH")
echo "PR created: $PR_URL"

echo "Waiting for checks to pass..."
gh pr checks "$BRANCH" --watch --interval 10

gh pr merge "$BRANCH" --squash --delete-branch || gh pr merge "$BRANCH" --squash --delete-branch --auto

git checkout main
git pull
git branch -d "$BRANCH" 2>/dev/null || true
